version: "3.9"

services:  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5000:80"
    networks:
      - gh_network
    environment:
      - UPLOAD_LIMIT=512M
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=300
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

networks:
  gh_network:
    external: true
    name: gh_network