const create = {
  type: "object",
  properties: {
    sub_categories_id: { type: ["string", "number"] },
    categories_id: {type: ["string", "number"]},
    product_name: { type: "string" },
    short_description: { type: "string" },
    brand_id: { type: "string" },
    full_description: { type: "string" },
    sku: { type: "string" },
    stock_quantity: { type: "string" },
    original_price: { type: "string" },
    offered_price: { type: "string" },
    uom_id: { type: "string" },
    available_start_date: { type: "string" },
    available_end_date: { type: "string" },
    is_active: { type: "string" },
  },
  required: [
    "sub_categories_id",
    "product_name",
    "categories_id",
    "full_description",
   // "sku",
    "brand_id",
   // "stock_quantity",
   // "available_start_date",
   // "uom_id",
  ],
  additionalProperties: true,
};

const excelCreate = {
  type: "object",
  properties: {
    sub_categories_id: { type: "integer" },
    product_name: { type: "string" },
    short_description: { type: "string", nullable: true },
    brand_id: { type: "integer" },
    full_description: { type: "string", nullable: true },
    sku: { type: "string", nullable: true },
    stock_quantity: { type: "integer", nullable: true },
    original_price: { type: "integer", nullable: true },
    offered_price: { type: "integer", nullable: true },
    uom_id: { type: "integer", nullable: true },
    available_start_date: { type: "string", nullable: true },
    available_end_date: { type: "string", nullable: true },
    is_active: { type: "integer", nullable: true },
    categories_id: { type: "integer", nullable: true },
    product_id: { type: "integer", nullable: true },
    seller_id: { type: "integer", nullable: true },
    product_type: { type: "string", nullable: true },
    is_tax_exempted: { type: "integer", nullable: true },
    tax_category_id: { type: "integer", nullable: true },
    hsn_code: { type: "string", nullable: true },
    oem_sku: { type: "string", nullable: true },
    legacy_sku: { type: "string", nullable: true },
    bar_code: { type: "string", nullable: true },
    disable_buy_button: { type: "integer", nullable: true },
    is_shown_in_home_page: { type: "integer", nullable: true },
  },
  required: [
    "sub_categories_id",
    "product_name",
    "brand_id",
    "categories_id",
    "uom_id",
  ],
  additionalProperties: false,
};

const excelUpdate = {
  type: "object",
  properties: {
    sub_categories_id: { type: "integer" },
    product_name: { type: "string" },
    short_description: { type: "string", nullable: true },
    brand_id: { type: "integer" },
    full_description: { type: "string", nullable: true },
    sku: { type: "string", nullable: true },
    stock_quantity: { type: "integer", nullable: true },
    original_price: { type: "integer", nullable: true },
    offered_price: { type: "integer", nullable: true },
    uom_id: { type: "integer", nullable: true },
    available_start_date: { type: "string", nullable: true },
    available_end_date: { type: "string", nullable: true },
    is_active: { type: "integer", nullable: true },
    categories_id: { type: "integer", nullable: true },
    product_id: { type: "integer", nullable: true },
    seller_id: { type: "integer", nullable: true },
    product_type: { type: "string", nullable: true },
    is_tax_exempted: { type: "integer", nullable: true },
    tax_category_id: { type: "integer", nullable: true },
    hsn_code: { type: "string", nullable: true },
    oem_sku: { type: "string", nullable: true },
    legacy_sku: { type: "string", nullable: true },
    bar_code: { type: "string", nullable: true },
    disable_buy_button: { type: "integer", nullable: true },
    is_shown_in_home_page: { type: "integer", nullable: true },
  },
  additionalProperties: false,
};

const productValidators = {
  create,
  excelCreate,
  excelUpdate,
};

export default productValidators;
